# Alternative colors 1. May be used to diferentiate projects in different editors.
 
inherits = "darcula-jesus"

"ui.background" = { bg = "bgColor" }
"ui.gutter" = { bg = "bgColor" }
"ui.linenr" = { fg = "grey03", bg = "bgColor" }
"ui.linenr.selected" = { fg = "grey04", bg = "bgColor", modifiers = ["bold"] }

[palette]
bgColor = "#1f1f28"
